### ISSUE TITLE
2024 講者介紹 - Dhrubajit Chowdhury

### ISSUE THREAD

**Issue by steven4program** [jsdc-core/blog.jsdc.tw#36]
# Dhrubajit Chowdhury

![dhru-pic](https://github.com/user-attachments/assets/d3514599-be10-4972-9d66-9c01251a3000)

`Web Performance` `Web Fundamentals`

Dhrubajit 是一位擁有超過 8 年經驗的資深軟體工程師、顧問與講師，他活躍於金融科技、物流與招聘等領域，致力於為客戶提供具影響力的技術解決方案與專業培訓。身為一位軟體與敏捷實踐的熱情倡導者，他曾在 JSConf.Asia 與 NightClazz 等知名活動中發表關於 Vue.js 與 React Hooks 的專題演講。

Dhrubajit 以其深厚的技術專長著稱，特別擅長構建動態的前端框架以及設計健全的後端系統架構，為團隊與企業創造可靠且高效的技術基礎。在 JSDC 2024 中，Dhrubajit 將以「Web Fundamentals for Performant Web Apps」為主題，帶領大家重溫網頁開發的基礎，探索如何優化加載時間、善用瀏覽器能力，並透過掌握基礎技術打造快速、穩定且可擴展的現代化網頁應用程式。敬請期待他帶來的精彩分享！

**Comment by clonn** [comment]
done
https://blog.jsdc.tw/2024/12/09/WebPerformance-Dhrubajit-speaker
