### ISSUE TITLE
2024講者介紹-Nicolò Ribaudo

### ISSUE THREAD

**Issue by JunLin525** [jsdc-core/blog.jsdc.tw#37]
只要是寫過js的開發者，多少都會用過babel的開源套件，而這次JSDC邀請到了babel.js的資深貢獻者Nicolò Ribaudo 來分享他在開發babel.js過程背後的趣味與心酸。
作為一個長期支持開源專案公司Igalia的資深員工，他將分享他在開發開源專案中遇到的各種狀況，也將提到如何藉由貢獻來讓整個開源專案更加推進。此議題，適合所有使用js的開發者或是對於開源專案感興趣的朋友。

購票火熱進行中，詳情點選連結購買

**Comment by clonn** [comment]
他好像還沒有提供大頭照！？

**Comment by v123582** [comment]
https://avatars.githubusercontent.com/u/7000710?v=4 @clonn

**Comment by clonn** [comment]
收到，在 Google sheet 裡面有

===================================
Caesar Chi.

Traveler and web developer.
Focus on open source group, member of Node.JS Taiwan Community.

About me,
http://about.me/clonn



WeiYuan ***@***.***>於 2024年12月9日 週一，16:27寫道：

**Comment by clonn** [comment]
2024-12-12-babeljs-nicolo.md
