### ISSUE TITLE
2024 講者介紹 - Vivian Yeh

### ISSUE THREAD

**Issue by LoisChen68** [jsdc-core/blog.jsdc.tw#42]
![Group 6](https://github.com/user-attachments/assets/6b8c563c-3936-4840-9bdd-056b413901a8)
你是否想將最新的 AI 技術整合進前端開發中，卻不知從何開始？JSDC 2024 很榮幸邀請到 Vivian Yeh，一位擁有三年開發經驗的軟體工程師，並同時經營 IG 自媒體 @vivian_enlife 分享職涯探索與自我成長的寶貴心得，她將為我們帶來主題為「輕鬆串接 Gemini API：從 Google AI Studio 到 Vertex AI in Firebase 的前端實作」的精彩分享。

在這場講座中，Vivian 將分享她在後端與 AI 服務開發上的豐富經驗，帶你一步步掌握 從 Google AI Studio 到 Vertex AI in Firebase 的前端實作。

🌟 議程亮點
- 探索 Gemini 模型的優勢，與學習 Google AI Studio 實作技巧
- 剖析 AI 服務融入前端時的潛在隱憂與解決方法
- 介紹與實作 Vertex AI in Firebase
- 分享自動化成本評估工具 Google APP Script
Vivian 更會以自身專注的技術領域為切入點，揭露她在 Firebase Vertex AI 與 Google AI Studio 的實戰心法，幫助你在開發中更有效率地運用 AI 服務！

無論你是對 AI 結合前端有興趣，還是想了解成本評估工具的實際運用技巧，這場講座都不容錯過！

**Comment by clonn** [comment]
2024-12-13-vivian-speaker.md
