### ISSUE TITLE
2024 講者介紹 - 黃冠融

### ISSUE THREAD

**Issue by v123582** [jsdc-core/blog.jsdc.tw#43]
## 2024 講者介紹 - 黃冠融

![](https://i.imgur.com/ZyywMxF.jpeg)

黃冠融是軟體工程師與技術顧問，現任 The Octalysis Group 軟體顧問及 Octalysis Prime 平台軟體工程師，專注於運用遊戲化提升用戶參與與企業效益。他自 19 歲踏入軟體行業，迅速成為遊戲化與專案管理領域的先驅之一，並於 2021 年獲得 CSP-SM 資格，累積豐富的敏捷實踐與團隊管理經驗。

多年來，他協助從初創企業到 HTC 等上市公司實現敏捷轉型，並透過遊戲化設計推動行為改變。本次邀請他參與 JSDC 議程，他將分享這幾年的工作經驗與心得。從 JavaScript 開發者到角度切入工程開發的管理視角，帶領大家深入了解技術與遊戲化的融合，啟發更多創新可能。

**Comment by clonn** [comment]
2024-12-14-KJH-speaker.md
