### ISSUE TITLE
2024 講者介紹 - 徐愷（KK）

### ISSUE THREAD

**Issue by v123582** [jsdc-core/blog.jsdc.tw#44]
## 2024 講者介紹 - 徐愷（KK）

![](https://ccmsassets.ithome.com.tw/2024/7/30/57a67dc1-2e53-4ba1-870b-668a1b858d4f.jpg)

徐愷（KK）是一位跨足商業與技術領域的雙棲實業家，從寫程式到探討程式，再到用程式助力他人成功。他熱衷於技術社群與交流活動，致力於透過科技創造價值，並讓身邊的人都能找到成功的契機。身為技術實踐者與創新推動者，KK 不僅專注於技術的深耕，也擅長用通俗易懂的方式，將技術概念轉化為實際應用。他相信科技是實現夢想的橋樑，而社群則是讓創意落地的最佳土壤。

這次邀請 KK 參與 JSDC 議程，他將分享他在商業與技術交叉點的洞見，以及如何透過技術助力個人與團隊達成目標。期待他的分享能激發更多人對科技與創業的熱情！

**Comment by clonn** [comment]
2024-12-13-kk-speaker.md
