### ISSUE TITLE
2024 講者介紹 - 後端里長伯

### ISSUE THREAD

**Issue by LoisChen68** [jsdc-core/blog.jsdc.tw#45]
![Group 11](https://github.com/user-attachments/assets/d9eb132b-a80f-47a9-908f-1641bb1c0c34)
在資料應用快速進化的時代，你是否好奇如何實現跨越文本、圖像，甚至多模態的搜尋功能？這次 JSDC 2024 很榮幸邀請到「後端里長伯」，一位總是關心「你的後端大小事」的技術大師，他將帶來精彩的議程：「向量搜尋與 Embedding Model 的進階應用」！

🎯 議程亮點
- 了解向量搜尋技術背後的基礎理論，揭開這項技術的神秘面紗
- 探討如何應用向量資料庫解決多模態搜尋需求，包括 圖搜文、文搜圖、音搜圖 等多樣化型態
- 深入學習 Google Multimodal 與 PG Vector 的實戰操作，從理論到實務一步到位

🌟 為什麼不能錯過這場分享？
傳統資料庫已無法滿足現代應用需求，特別是在圖文搜尋和多模態資料整合的領域。本議程將帶你領略向量技術如何幫助開發者突破技術瓶頸，建構下一代的資料檢索解決方案！

趕快和你的技術夥伴一起來參與這場精彩的分享，為你的技術栈注入新能量吧！ 🔥

**Comment by clonn** [comment]
2024-12-14-hohshen-speaker.md
