### ISSUE TITLE
2024 講者介紹 - Codefarmer

### ISSUE THREAD

**Issue by LoisChen68** [jsdc-core/blog.jsdc.tw#46]
![Group 10](https://github.com/user-attachments/assets/4277da32-bb21-47a2-a5b9-c9e5b95c8c19)
JavaScript 的生態系正在悄悄發生變革，你準備好迎接了嗎？JSDC 2024 很榮幸邀請到了熱愛技術分享的 codefarmer，這位專注於前端領域的 webdev 小碼農，他將為我們帶來精彩的議程：「一起探索 VoidZero：JS 生態系的下一把瑞士刀」，深入了解 VoidZero 為 JavaScript 開發者準備的全新工具鏈！

🌟  這場分享將帶你了解：
- VoidZero 工具鏈的整合之道：如何將 Vite、Vitest、Rollup、Oxc 等工具無縫結合，打造一套高效且通用的開發工具組，包括建構工具 (build tool)、測試框架 (test runner)、打包工具 (bundler)、與程式碼檢查工具 (linter)，全面提升開發者體驗
- 深入探索新興工具：以淺入深的方式，帶你了解這些工具的核心功能及最佳應用場景，發掘它們在實際專案中的效率提升秘訣
- 洞見 VoidZero 的未來影響力：剖析 VoidZero 對 JavaScript 生態系的影響與潛力

📅 別錯過這場精彩議程！
立即標記你的技術同好，一起來 JSDC 2024 了解這把為 JavaScript 生態系準備的「瑞士刀」吧！

**Comment by clonn** [comment]
_posts/2024-12-14-Codefarmer-vite.md
