### ISSUE TITLE
2024講者介紹- 閻祥溥 (Andy)

### ISSUE THREAD

**Issue by JunLin525** [jsdc-core/blog.jsdc.tw#47]
作為一個開發者，怎樣寫出一個好的SQL來跟資料庫互動是日常常常碰到的難題，不論是效能或是join的難題，常常都會思考怎樣可以把整個資料擷取過程更加優化。
而此次，在易開科技服務的Andy將分享自家的開源解方Wren AI，都可以透過這個開源專案用簡單的問句來更簡化你索取資料的流程，而在分享當中Andy也將更深入的討論Ｗren Ai的開發與其架構，不論你是PM、資料庫新手或是追求開發效率的senior相信都能在這場議程中有所啟發。
想知道更多有關資料擷取痛點的解方，就即刻買票參與JSDC2024吧！

**Comment by clonn** [comment]
2024-12-13-andy-yen-wrenai.md
